### ISSUE TITLE
Plugin should support babel presetenv options. As of now this is hardcoded to {spec:true}

### ISSUE THREAD

**Issue by gautam1109** [erictooth/pika-plugin-legacy-browser#6]

**Comment by gautam1109** [comment]
This change could be to pass presetEnvOptions

presets: [
                    [
                        babelPresetEnv,
                        {
                            spec: true,
                            **...babelOptions.presetEnvOptions,**
                        },
                    ],
                    ...(babelOptions.presets || []),
                ],

**Comment by erictooth** [comment]
Fixed by #7
